default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: n
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: framgia-glob_development

test:
  <<: *default
  database: framgia-glob_test

production:
  <<: *default
  database: framgia-glob_production
  username: framgia-glob
  password: <%= ENV['FRAMGIA-GLOB_DATABASE_PASSWORD'] %>
